# Use a Python base image
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:1.2-1-cpu-py3

# Set the working directory
WORKDIR /app

# Copy files to the container
COPY requirements_train.txt ./
COPY dict_mats_dB.npy ./
COPY audio_ds_model.py ./
COPY timing_decor.py ./
COPY training_func.py ./
COPY training_script_big.py ./
COPY encoded_labels.npy ./
    
RUN pip install -r requirements_train.txt

# Command to run the app
CMD ["sh", "-c", "python training_script_big.py"]
